/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_alpha.h"
#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_status2d.h"
#include "bar_statusbutton.h"
#include "bar_winicon.h"
#include "bar_tags.h"
#include "bar_wintitle.h"

/* Other patches */
#include "attachx.h"
#include "cfacts.h"
#include "cool_autostart.h"
#include "cyclelayouts.h"
#include "dwmc.h"
#include "floatpos.h"
#include "focusadjacenttag.h"
#include "pertag.h"
#include "restartsig.h"
#include "rotatestack.h"
#include "renamed_scratchpads.h"
#include "seamless_restart.h"
#include "setborderpx.h"
#include "sticky.h"
#include "swallow.h"
#include "togglefullscreen.h"
#include "vanitygaps.h"
#include "warp.h"
#include "xrdb.h"
/* Layouts */
#include "layout_bstack.h"
#include "layout_columns.h"
#include "layout_gapplessgrid.h"
#include "layout_monocle.h"
#include "layout_tile.h"

