#!/usr/bin/env bash

signal() {
	xsetroot -name "fsignal:$*"
}

case $# in
1)
	case $1 in
	defaultgaps) ;&
	focusurgent) ;&
	fullscreen) ;&
	killclient) ;&
	mirrorlayout) ;&
	mpdcontrol) ;&
	pushdown) ;&
	pushup) ;&
	self_restart) ;&
	setcfact) ;&
	setlayout) ;&
	switchcol) ;&
	tagandviewtoleft) ;&
	tagandviewtoright) ;&
	tagtoleft) ;&
	tagtoright) ;&
	togglealttag) ;&
	togglebar) ;&
	togglefakefullscreen) ;&
	togglefloating) ;&
	togglefullscreen) ;&
	togglegaps) ;&
	togglehorizontalmax) ;&
	togglemax) ;&
	togglesticky) ;&
	toggleverticalmax) ;&
	transfer) ;&
	transferall) ;&
	unfloatvisible) ;&
	view) ;&
	viewall) ;&
	viewtoleft) ;&
	viewtoright) ;&
	winview) ;&
	xrdb) ;&
	zoom)
		signal $1
		;;
	*)
		echo "Unknown command ($1) or missing one argument."
		exit 1
		;;
	esac
	;;
2)
	case $1 in
	cyclelayout) ;&
	explace) ;&
	moveplace) ;&
	mpdchange) ;&
	setkeymode) ;&
	switchtag) ;&
	togglescratch) ;&
	view)
		signal $1 ui $2
		;;
	focusmon) ;&
	focusstack) ;&
	incnmaster) ;&
	incnstack) ;&
	incrgaps) ;&
	incrigaps) ;&
	incrihgaps) ;&
	incrivgaps) ;&
	incrogaps) ;&
	incrohgaps) ;&
	incrovgaps) ;&
	inplacerotate) ;&
	movestack) ;&
	pushstack) ;&
    quit) ;&
	rotatelayoutaxis) ;&
	rotatestack) ;&
	setborderpx) ;&
	setgaps) ;&
	setlayoutaxisex) ;&
	setlayoutex) ;&
	shiftview) ;&
	shiftviewclients) ;&
	swapfocus) ;&
	tagallmon) ;&
	tagex) ;&
	tagmon) ;&
	tagswapmon) ;&
	toggletagex) ;&
	toggleviewex) ;&
	viewex)
		signal $1 i $2
		;;
	setcfact) ;&
	setmfact)
		signal $1 f $2
		;;
	*)
		echo "Unknown command ($1) or too many arguments"
		exit 1
		;;
	esac
	;;
5)
	case $1 in
	setgaps)
		# Expects "setgaps oh ov ih iv" where -1 means to keep existing values
		[ $2 = -1 ] && oh=128 || oh=$2
		[ $3 = -1 ] && ov=128 || ov=$3
		[ $4 = -1 ] && ih=128 || ih=$4
		[ $5 = -1 ] && iv=128 || iv=$5
		signal $1 i $(((oh << 24) + (ov << 16) + (ih << 8) + iv))
		;;
	*)
		echo "Unknown command ($1) or too many arguments"
		exit 1
		;;
	esac
	;;
*)
	echo "Unknown command ($1) or too many arguments"
	exit 1
	;;
esac

